# Generated by Django 2.2.4 on 2019-08-26 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ManyToManyField(related_name='studentinterest', to='app.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('local', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], default='Married', max_length=25)),
                ('profilepic', models.ImageField(blank=True, upload_to='profile/')),
                ('valid', models.ImageField(blank=True, upload_to='identification/%Y/%m/%d')),
                ('appointment', models.ImageField(blank=True, upload_to='identification/%Y/%m/%d')),
                ('cadre', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True)),
                ('process', models.BooleanField(default=False)),
                ('proceed', models.BooleanField(default=False)),
                ('trailperiod', models.DateTimeField(default=teacher.models.get_deadline)),
                ('fullperiod', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='teacher.Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
